### PR TITLE
Persistence

### PR DESCRIPTION
**Pull request by Atema**
Persist relevant parts of the Redux store in Firebase

Also, keep Spotify auth info in the normal Redux store instead of just Firebase.

### CODE REVIEW

**Comment by Atema** [comment]
**Note**: As only the second part is done atm, persistence is completely broken in this current version

**Comment by nikolim** [comment]
Thanks for taking over this part! Could we also save the played and banned songs in Firebase?

**Comment by Atema** [comment]
> Thanks for taking over this part! Could we also save the played and banned songs in Firebase?

That's the goal :)

**Comment by Atema** [comment]
It now should have the same functionality as before (persists the access token), and can be extended relatively easily.

**Pull request merged**
