### PR TITLE
Added basic styling to tic-tac-toe

### PR DESCRIPTION
**Pull request by nikolim**
Replaced the css-module with some simple tailwind styling

### CODE REVIEW

**Review by vanFrZy — APPROVED** [review]
LGTM

**Comment by Atema** [comment]
Gonna take a look at this now, so please don't merge just yet :)

**Comment by Atema** [comment]
Nice job overall!

I've made a few changes to try and make it even better:

- Remove Square component: it clashed a bit with the one component per file directive, and felt like it wasn't really needed anyway
- Make spacing responsive to parent container: give it a bit more breathring room, and make sure it doesn't overflow the box
- Add hover effect when selecing box: semi-solves #86, although there's still unclarity when both have the same album cover.
- Making left icons a bit rounder: put them in harmony with each other a bit more
- Disable button when icon is placed (and remove magnify effect): these made it feel like you needed to press the already placed icons

Please take a look and let me know what you think :)

**Comment by nikolim** [comment]
Looks and feel really good! Thanks for improving it

**Pull request merged**
